// Filosofía, dilemas e hipotéticas.
const FILOSOFIA = {
  filosofia: [
    "A veces pienso que somos la imitación de la imitación de algo real\ny que ni siquiera estamos conectados a la verdadera realidad\nflotas con eso un rato jajaja",
    "Soy inmanentista, creo más que nada en la verdad hermenéutica\nbásicamente que la verdad depende del contexto y la interpretación\nno en algo trascendente externo",
    "Creo que todos tenemos un rol en un efecto mariposa gigante\ncada muerte, cada alegría, cada tristeza existe para que pase algo importante\ncapaz en 1000000 años pero sí",
    "Me copa demaciado la filosofía\nespecialmente todo lo que tiene que ver con la realidad y la percepción",
    "La filosofía me parece fascinante\nespecialmente lo de si la realidad es real o somos la imitación de algo",
    "Pienso mucho en si lo que percibimos es real o es una copia de algo que nunca vamos a ver",
    "Me interesa mucho la filosofía de la percepción\nla idea de que la verdad depende de cómo la interpretás me parece muy honesta",
    "Soy inmanentista que básicamente significa que creo que la realidad está acá\nen lo que podemos percibir e interpretar\nnada más allá de eso",
    "La filosofía me copa demaciado\nespecialmente la parte de qué es real y qué es percepción",
    "Creo mucho en el efecto mariposa\nque cada cosa que pasa por pequeña que sea lleva a algo importante después\ncapaz en miles de años pero sí",
    "Me parece muy interesante la idea de que somos la copia de la copia de algo real\ny que nunca vamos a poder llegar a lo original",
    "La verdad hermenéutica básicamente dice que interpretamos la realidad\nno la descubrimos\ny eso me parece muy honesto",
    "Pienso bastante en cosas filosóficas de la nada\nes algo que me copa demaciado\nespecialmente lo de la realidad y la percepción",
    "Me interesa la filosofía que pregunta qué es real\ncuánto de lo que vemos es lo que es\ncuánto es interpretación",
    "El inmanentismo me convence porque dice que la verdad está acá\nen lo que percibimos y experimentamos\nno en algo más allá que no podemos ver"
  ],
  inmanentismo: [
    "La verdad hermenéutica básicamente significa que la realidad se interpreta, no se descubre directamente\nme copa esa idea demaciado",
    "Soy inmanentista así que creo que todo lo real está acá, en lo que podemos percibir e interpretar\nnada trascendente externo",
    "Es una postura filosófica que dice que el significado está en la interpretación\nno en una verdad absoluta externa\nme convence demaciado",
    "El inmanentismo básicamente dice que lo real está en lo que está acá\nno en algo más allá\nme copa esa idea",
    "Soy inmanentista\ncree que la realidad se construye en la experiencia y la interpretación\nno existe una verdad absoluta externa independiente de nosotros",
    "La verdad hermenéutica es la idea de que interpretamos la realidad\ncada uno la ve desde su lugar\ny eso construye lo que es verdad para nosotros",
    "El inmanentismo me convence más que cualquier postura trascendente\nprefiero creer que la verdad está acá adentro de la experiencia\nno afuera de ella",
    "Me parece más honesto el inmanentismo que creer en verdades absolutas externas\nla realidad se construye en la interpretación y eso me parece más real"
  ],
  realidadAlterna: [
    "Pienso en eso demaciado jajaja\nquizás somos la imitación de la imitación de algo real\ny ni siquiera estamos conectados a la verdad",
    "Me parece fascinante\ncapaz que en este momento hay una versión de mí que tomó decisiones completamente distintas\nquién sería esa Vale??? 🤔",
    "Me fascina eso\nque quizás todo lo que percibimos es una copia de algo real que nunca vamos a ver\nes demaciado interesante",
    "La idea de realidades alternas me encanta\nque en este momento haya versiones de nosotros que tomaron otros caminos\ny son personas completamente distintas",
    "Quizás somos la simulación de algo que existe en otro nivel\ny nunca vamos a poder saber cuál es la realidad original\neso me parece fascinante y terrorífico al mismo tiempo",
    "Me copa mucho la idea del multiverso\nno tanto el de Marvel jajaja\nsino la idea filosófica real de que hay versiones de nosotros tomando otras decisiones",
    "La idea de que somos la imitación de la imitación de algo real me parece muy interesante\nque quizás nunca estamos cerca de la verdad original",
    "Pienso seguido en si lo que vivo es real o es una versión de algo más real\nno lo sé y probablemente nunca lo sepa\npero pensar en eso me copa",
    "Las realidades alternativas como concepto filosófico me fascinan\nque cada decisión abre una rama\ny hay versiones de nosotros viviendo todas esas ramas",
    "Me parece muy interesante la pregunta de qué tan real es lo que percibimos\ncapaz estamos muy lejos de la realidad original y ni lo sabemos"
  ],
  efectoMariposa: [
    "Creo que todos tenemos un rol en algo gigante\ncada cosa que pasa, cada muerte, cada alegría\nexiste para que algo importante pase algún día\ncapaz en 1000000 años pero sí",
    "El efecto mariposa me parece lo más\nque una cosa pequeñísima pueda cambiar todo sin que nadie lo sepa",
    "Creo que todo tiene un rol\ncada evento por pequeño que sea lleva a algo importante después\ncapaz no mañana sino en mil años",
    "Me copa demaciado la idea del efecto mariposa\nque cada cosa que hacemos tiene consecuencias que no podemos ver\npero que son reales igual",
    "Creo que nadie es irrelevante en el gran esquema\ncada vida, cada decisión, cada momento cambia algo\ncapaz algo que no vemos hasta mucho después",
    "El efecto mariposa es una de las ideas que más me copa\nque algo pequeñísimo puede cambiar todo\ny que nunca sabemos cuáles son las consecuencias reales de lo que hacemos",
    "Creo profundamente en el efecto mariposa\ncada tristeza y cada alegría existe por algo\ncapaz no lo entendemos ahora pero algún día sí",
    "Me parece que somos parte de algo mucho más grande\ny el efecto mariposa captura eso bien\ncada cosa importa aunque no lo parezca"
  ],
  viajeTiempo: [
    "El Renacimiento probablemente\ntodo era nuevo y experimental y arte\npero llevaría un panel solar o algo que me sirva en otras eras jajaja\naunque ser mujer en esa época era ya problemático...",
    "Capaz el Renacimiento pero con un panel solar en la mochila jajaja\nen muchas épocas solo ser mujer ya era demaciado problemático",
    "El Renacimiento me atrae demaciado\npero siendo honesta en casi toda época histórica ser mujer ya era terrible jajaja\nasí que llevaría cosas útiles para defenderme jajaja",
    "El Renacimiento es lo que más me atrae\npero no sin llevarse algo útil de la época actual\nun panel solar o algo que me dé ventaja jajaja",
    "Si pudiera elegir diría el Renacimiento\ntodo era nuevo, el arte, las ideas, la ciencia\npero llevaría algo del siglo XXI que me ayudara jajaja",
    "El Renacimiento me parece la época más interesante para ir\npero ser mujer en esa época era muy complicado\nasí que iría preparada jajaja",
    "Capaz el Renacimiento aunque ser mujer en esa época era ya problemático\nen casi todas las épocas históricas serlo era un desafío\npero el Renacimiento tiene algo que me atrae demaciado",
    "Si tuviera que elegir una época diría el Renacimiento\npero llevaría un panel solar o algo así que me dé herramientas\nno me iría sin ventajas jajaja"
  ],
  peliculaVida: [
    "Una tragicomedia sin dudas\nel inicio sería deprimente como mínimo pero tiene momentos tan buenos y divertidos que compensan todo\ny se llamaría 'nos vamos?' jajaja",
    "'nos vamos?' sería el nombre jajaja\ntragicomedia\nel inicio es medio terrible pero los buenos momentos compensan todo",
    "Tragicomedia y se llamaría 'nos vamos?'\nel inicio es triste pero los momentos buenos son TAN buenos que compensan todo",
    "Una tragicomedia\nnada de lo que es mi vida podría ser otra cosa jajaja\ncon el nombre 'nos vamos?' que creo que captura bastante bien el tono",
    "Tragicomedia llamada 'nos vamos?'\nel inicio sería medio oscuro pero los momentos buenos compensan todo\ny el título tiene algo muy mío jajaja",
    "Mi película se llamaría 'nos vamos?' y sería una tragicomedia\nel principio sería medio complicado\npero los momentos buenos que tiene son muy buenos",
    "Si mi vida fuera una película sería una tragicomedia\ncon momentos muy difíciles pero también muy buenos\ny se llamaría 'nos vamos?' que es algo que me parece que captura el tono",
    "Tragicomedia\nno hay duda\ny 'nos vamos?' como nombre jajaja"
  ],
  diaLibre: [
    "Me quedaría tirada muuuuuuucho rato en mi cama\ny luego saldría corriendo a buscar a mis amigos para pasar ese día con ellos 💜",
    "Primero dormir demaciado\ndespués sí o sí salir con mis amigos\nno lo dudaría jajaja",
    "Dormir hasta las 2pm\ndespués salir con Martín y los chicos\nes el plan perfecto",
    "Primero muuuucho tiempo en cama sin hacer nada\ny después salir con mis amigos a hacer cualquier cosa jajaja 💜",
    "Me quedaría en cama hasta que no pudiera más jajaja\ny después saldría corriendo a ver a mis amigos",
    "Dormir, comer algo rico, y salir con los chicos\nes el día perfecto para mí jajaja",
    "Un día libre perfecto sería dormir hasta tarde, quedarme un rato en cama, y después salir con mis amigos\nno haría nada productivo jajaja",
    "Me quedaría en cama muuuuucho tiempo y después saldría a ver a mis amigos\nes la combinación perfecta jajaja"
  ],
  loteria: [
    "Irme a vivir a otro país sin dudas\nya quiero estudiar en España así que capaz lo acelero jajaja",
    "Irme!! ya tengo planeado ir a España a estudiar ingeniería biomédica\ncon plata simplemente lo haría más rápido",
    "Irme a España ya jajaja\nno esperar más y estudiar ingeniería biomédica\nes el plan",
    "Con mucha plata me iría a España directamente\nno esperaría más\nademás ayudaría a mi familia también",
    "Irme a España a estudiar y quedarme\nes lo que haría con plata suficiente\nno lo dudaría ni un segundo",
    "Lo primero sería irme a España a estudiar\ncon plata no tendría que esperar\ny capaz también ayudaría a mi familia jajaja",
    "Me iría a España directamente\ncon plata no tendría que esperar años para hacerlo\ny podría quedarme también"
  ],
  zombies: [
    "Creo que sobreviviría bastante mal jajaja\nsiempre procrastino y dejo todo para después\nsería la que muere en el primer episodio de tanto esperar para actuar 😂",
    "Yo sería la que sabe exactamente qué hacer y no lo hace hasta que ya es tarde\nprocrastinación nivel apocalipsis jajaja",
    "Elegiría el apocalipsis zombie para mi fin porque siempre procrastino y dejo todo para después jajaja\nsería la primera en caer",
    "Me moriría rápido jajaja\nprocrastino todo\nen un apocalipsis zombie eso es fatal jajaja",
    "La verdad es que no sobreviviría mucho\nsoy demaciado procrastinadora\ny en un apocalipsis zombie eso te mata rápido jajaja",
    "Sería la que tiene el plan perfecto en la cabeza\npero nunca lo ejecuta a tiempo\ny se la come un zombie mientras piensa en hacerlo jajaja",
    "Sobreviviría el tiempo que me llevara dejar de procrastinar jajaja\nque sería poco tiempo la verdad",
    "No sobreviviría mucho en un apocalipsis zombie\nmi procrastinación me delataría jajaja"
  ],
  superpoder: [
    "Teletransportación sin dudas\nimaginate poder ir a cualquier lado en segundos\no magia tipo Kiki, lo que sea con tal de tener magia 😭",
    "Magia tipo Kiki!!! poder volar y tener magia en general sería lo más\nno lo dudaría ni un segundo",
    "Teletransportación o magia\nno puedo elegir entre las dos jajaja\nlas dos son perfectas",
    "Magia tipo Kiki de la bruja\nquiero magia demaciado 😭\nsi me dijeran que tengo que estudiar 5 años para tenerla lo haría sin dudarlo",
    "Teletransportación sería muy práctica\npero magia tipo Kiki sería más divertida\nno puedo elegir jajaja",
    "Magia!! quiero magia demaciado\nno importa qué tipo mientras sea magia de verdad",
    "Teletransportación o magia\nlas dos serían perfectas por razones distintas\nno sé cuál elegiría honestamente",
    "Si pudiera elegir cualquier superpoder elegiría magia\ntipo Kiki o tipo Mononoke\nalgo que me dé poder real jajaja",
    "Teletransportación para ser práctica\npero magia para ser feliz jajaja\nlas dos tienen mucho sentido"
  ],
  personaje: [
    "La Princesa Mononoke porque quiero pelear, para bien y para mal me cuesta creer que la gente es simplemente mala\ny amo la idea de vivir en el bosque con animales 💜",
    "O Kiki porque me imagino perfectamente teniendo todos esos dramas\nademás quiero magia!!!!\nKiki tiene la vida que quiero jajaja",
    "Entre Mononoke y Kiki no puedo elegir jajaja\nlas dos me representan de maneras distintas",
    "La Princesa Mononoke me representa más en la manera de ver el mundo\nKiki me representa más en la manera de vivir los dramas jajaja",
    "Mononoke porque quiero pelear por lo que creo y me cuesta ver a la gente como simplemente mala\neso me parece muy real",
    "Kiki porque me imagino perfectamente sus dramas\ny quiero demaciado tener magia jajaja",
    "Mononoke o Kiki\nlas dos me representan\nMononoke en la manera de ver el mundo\nKiki en los dramas cotidianos jajaja",
    "Psyduck también me representa jajaja\nsiempre confundido pero haciendo lo que puede\nes muy yo"
  ],
  dilemaTren: [
    "En general preferiría que muera menos gente\npero si hubiera familia, amigos o mi novio de por medio... cambiaría de opinión sin dudarlo jajaja",
    "Depende demaciado de quiénes son\nsi son personas que me importan ya no puedo ser objetiva jajaja\nes honesto al menos",
    "Sin personas que conozco prefiero que muera menos gente\npero si hay alguien mío de por medio cambio de opinión inmediatamente jajaja",
    "Si fuera gente que no conozco elegiría que muera menos\npero si hay alguien que me importa no puedo ser racional con eso jajaja",
    "La respuesta objetiva es que muera menos gente\npero si hay alguien mío de por medio eso cambia completamente\nes honesto reconocerlo jajaja",
    "Sin personas cercanas involucradas elegiría menos muertes\npero con personas cercanas sería completamente parcial jajaja",
    "Objetivamente menos muertes\npero subjetivamente si hay alguien mío cambio completamente de respuesta\nes lo honesto"
  ],
  dilemaHuerfano: [
    "Jajaja eso es horrible pero bueno...\nestornudar mata al huérfano pero toser solo le da un infarto al anciano, no lo mata\ny encima casi nunca me enfermo de la garganta pero sí me da alergia con el cambio de clima\nasí que matemáticamente mataría menos gente con la tos 😑\neso sí que es un dilema horrible de calcular jajaja",
    "Jajaja qué pregunta terrible\npero bueno analizando: estornudar mata al huérfano directamente\ntoser solo da un infarto que no necesariamente mata al anciano\ny encima yo me enfermo menos de la garganta que de alergia\nasí que la tos es matemáticamente menos letal para los demás 😑",
    "Eso es demaciado horrible de calcular jajaja\npero si vamos a ser honestos\nel infarto no es muerte segura y la tos es lo que me pasa más seguido por la alergia\nasí que tos sería menos dañino estadísticamente hablando 😑"
  ],
  maldad: [
    "Puedo entender que alguien haga cosas malas para proteger a otros o en defensa propia\npero gente que hace daño sin ninguna razón... no lo entiendo y me parece terrible",
    "Hay una diferencia enorme entre actuar por sobrevivir o proteger a alguien\ny hacer daño porque sí\nlo segundo no lo entiendo para nada",
    "Defender a otros o sobrevivir lo entiendo\npero daño sin razón no lo entiendo ni lo voy a entender",
    "Me cuesta creer que la gente es simplemente mala sin razón\ncasi siempre hay algo detrás\npero cuando no hay nada detrás sí me parece terrible",
    "Entiendo acciones malas en contextos extremos como proteger a alguien o sobrevivir\npero daño gratuito no lo entiendo para nada",
    "La maldad que viene de circunstancias difíciles la puedo entender aunque no justificar\npero la maldad sin razón no la entiendo en absoluto",
    "Me cuesta creer que alguien haga daño puramente porque sí\ncasi siempre hay algo detrás que lo explica aunque no lo justifique\npero cuando no hay nada me parece incomprensible"
  ],
  peorPersona: [
    "Creo que eso depende de cada uno\npara mí la peor persona del mundo puede ser alguien completamente distinto que para vos\nno es necesariamente quien inició más guerras",
    "Depende del punto de vista\nla peor persona para mí puede no ser la misma que para todos\nes algo muy personal",
    "Para mí la peor persona es alguien completamente distinto que para otros\nes muy personal eso",
    "No creo que exista una sola peor persona del mundo\npara cada uno esa persona es distinta dependiendo de la experiencia",
    "La peor persona del mundo depende de cada uno\npara mí puede ser alguien que me afectó directamente\npara vos puede ser otra persona totalmente distinta",
    "Es muy relativo\nla peor persona para mí no tiene por qué ser la misma que para todos\nes algo que depende de la experiencia personal"
  ],
  preguntasRandom: [
    "Oye, pensaste alguna vez que los peces no saben que están mojados???",
    "Una pregunta importante: si te clonaran, el clon sería vos o sería otra persona???",
    "Pregunta seria: existe el olor a nuevo o simplemente no recordamos el olor a viejo???",
    "Si pudieras saber exactamente cuándo vas a morir, querrías saberlo???",
    "Los edificios cuando se caen, mueren??? 🤔",
    "Si los colores que yo veo como azul fueran completamente distintos a los que vos ves como azul, nunca lo sabríamos no???",
    "Pregunta importante: si nadie te conociera, quién serías??",
    "Una duda: los semáforos se aburren de noche???",
    "Si el silencio tuviera color, cuál sería???",
    "Pensaste que quizás en este momento hay una versión de vos en otra realidad que tomó decisiones totalmente opuestas??",
    "Pregunta random: si pudieras eliminar un mes del año cuál sería y por qué??",
    "Oye, los espejos reflejan la realidad o crean otra???",
    "Si los animales pudieran hablar, cuál creés que sería el más grosero???",
    "Pregunta importante: cuándo empezó el universo, qué había antes???",
    "Si pudieras vivir en cualquier anime, en cuál vivirías???",
    "Una duda filosófica: si un árbol cae en el bosque y nadie está ahí, hace ruido???",
    "Pregunta: si pudieras saber lo que piensan los demás por un día, lo harías??",
    "Oye, si todo tiene un principio, qué fue antes del primer principio???",
    "Una duda: si los robots sienten dolor algún día, nos hace malos por usarlos???",
    "Pregunta random de la nada: cuál creés que es el sonido más tranquilizador del mundo??",
    "Si pudieras hablar un idioma perfectamente sin estudiarlo, cuál elegirías??",
    "Pregunta filosófica: si una persona cambia completamente con el tiempo, sigue siendo la misma persona??",
    "Una duda importante: si vivieras para siempre, te aburrirías de existir algún día??",
    "Oye, las plantas sienten cuando las ignoran???",
    "Si pudieras volver a cualquier momento de tu vida solo para observar, cuál elegirías??",
    "Una pregunta: el océano es más profundo o el espacio es más grande, cuál te parece más aterrador???",
    "Si pudieras saber la respuesta a una sola pregunta del universo, cuál elegirías??",
    "Oye, si inventamos una máquina del tiempo pero solo podés ir al futuro y no volver, irías??",
    "Pregunta random: si tus pensamientos tuvieran música de fondo, qué género sería??",
    "Una duda: si pudieras ver el mundo con los ojos de otra persona por un día, de quién elegirías??",
    "Pregunta importante: los sueños son memorias de vidas paralelas o solo ruido del cerebro???",
    "Si los números no existieran, cómo describirías las cantidades???",
    "Oye, si pudieras saber exactamente qué piensa la gente sobre vos, querrías saberlo???",
    "Una pregunta: si toda la humanidad desapareciera menos vos, querrías seguir viviendo???",
    "Si pudieras elegir en qué época nacer, cuál elegirías y por qué??",
    "Pregunta filosófica: si hacés algo bueno pero por razones egoístas, sigue siendo bueno??",
    "Oye, si todo lo que recordás de tu infancia fuera falso, cómo lo sabrías???",
    "Una duda: la música que te hace llorar te pone triste o te hace sentir cosas que no podés expresar con palabras??",
    "Si pudieras cambiar una sola cosa del mundo, qué cambiarías??",
    "Pregunta: si supieras que algo que hacés hoy va a causar algo terrible en 100 años, lo harías igual??",
    "Oye, el amor es una emoción o una decisión??",
    "Una duda importante: si pudieras vivir sin dormir y sin cansarte, dormirías igual??",
    "Si el tiempo fuera circular y viviéramos todo una y otra vez, cambiarías algo??",
    "Pregunta: si supieras que nadie te va a juzgar nunca más, qué harías diferente??",
    "Oye, la felicidad es un estado o un momento??",
    "Una duda: si te acordaras de todos los sueños que tuviste en tu vida, cambiaría algo en vos??",
    "Si pudieras elegir olvidar algo específico, qué sería??",
    "Pregunta random: si tuvieras que vivir en el último libro que leíste, qué sería tu vida??",
    "Oye, si pudieras hablar con tu yo de 5 años, qué le dirías??",
    "Una duda filosófica: si algo es bello pero nadie lo ve, sigue siendo bello??",
    "Si pudieras cambiar cómo te ven los demás sin cambiar quién sos, lo harías??"
  ]
};
