// Banco MEGA2 convertido del generador Python original.
const MEGA2 = {
  reacciones_bien: [
    "Jajaja qué bueno!! 💜",
    "Re!! qué copado",
    "Buenísimo jajaja",
    "Ay qué bien!! 💜",
    "Re copado!!",
    "Jajaja qué bueno eso",
    "Ay qué bueno!! jajaja",
    "Copado copado!! 💜",
    "Re jajaja qué bien",
    "Buenísimo!! 💜",
    "Jajaja re copado eso",
    "Ay qué bueno 💜",
    "Re!!! qué copado jajaja",
    "Jajaja buenísimo!!",
    "Ay qué bien eso!! 💜",
    "Re copado jajaja!!",
    "Buenísimo!! jajaja 💜",
    "Ay qué bien!! qué copado",
    "Jajaja re!! muy bien",
    "Copado!! 💜 jajaja"
  ],
  reacciones_mal: [
    "Ay no 😭 qué feo",
    "Uff qué mal 😭",
    "Nooo 😭 qué tiene?",
    "Ay qué feo eso 😭",
    "Uff 😭 qué pasó?",
    "Ay no qué mal 😭",
    "Nooo qué feo 😭",
    "Uff ay no 😭",
    "Ay qué mal eso 😭",
    "Nooo qué tiene 😭",
    "Uff qué feo 😭",
    "Ay no 😭 qué onda?",
    "Nooo 😭 qué fue?",
    "Uff 😭 qué pasó?",
    "Ay no qué feo 😭",
    "Nooo 😭 qué tiene?",
    "Uff ay no qué mal 😭",
    "Ay no 😭 contame",
    "Nooo 😭 qué pasó?",
    "Uff qué mal eso 😭"
  ],
  reacciones_gracioso: [
    "Jajajajaja 😂 no puedo",
    "Jajaja terrible 😂",
    "Jajajajaja eso estuvo muy bueno",
    "Jajaja me reí 😂",
    "Jajajajaja buenísimo",
    "Jajaja terrible terrible 😂",
    "Jajajaja 😂 muy bueno",
    "Jajaja me reí mucho 😂",
    "Jajajajaja no puedo 😂",
    "Jajaja muy bueno jajaja 😂",
    "Jajajajaja horrible 😂",
    "Jajaja 😂 buenísimo eso",
    "Jajajajajaja no 😂",
    "Jajaja terrible jajaja 😂",
    "Jajajaja muy bueno 😂",
    "Jajaja no puedo 😂",
    "Jajajaja buenísimo 😂",
    "Jajaja me reí demaciado 😂",
    "Jajajajaja eso estuvo bueno 😂",
    "Jajaja no puedo jajaja 😂"
  ],
  confirmaciones: [
    "Jajaja ta 💜",
    "Oka",
    "Re 😎",
    "Jaja ta",
    "💜",
    "Jajaja re",
    "Ta jaja",
    "Ajá jajaja",
    "Re ta",
    "Mm jaja",
    "Jaja sí",
    "Ta ta jajaja",
    "Re re 😎",
    "Oka ta",
    "Jajaja dale",
    "Ta 💜",
    "Mm ta",
    "Jajaja oka",
    "Re!! ta",
    "Oka jajaja",
    "Jajaja sí ta",
    "Re jaja ta",
    "Oka oka",
    "Jaja dale",
    "Ta 😎",
    "Re!! jajaja",
    "Oka dale 💜",
    "Jajaja ta ta",
    "Re ta ta",
    "Mm sí jajaja"
  ],
  chau_extra: [
    "Chau!! 💜",
    "Dale, chau!!",
    "Chau chau 💜",
    "Dale cuídate!! 💜",
    "Chau!! hablamos",
    "Nos vemos!! 💜",
    "Chauuu!! 💜",
    "Dale!! 💜 hablamos",
    "Chau!! 💜 cuídate",
    "Hasta luego!! 💜",
    "Dale chau chau!! 💜",
    "Chau!! nos vemos",
    "Cuídate!! 💜 chau",
    "Hasta!! 💜",
    "Chau chau!! cuídate 💜",
    "Chau!! 💜 después hablamos",
    "Dale cuídate!!",
    "Chau!! 💜 hablamos después",
    "Hasta!! cuídate 💜",
    "Chauuu cuídate!! 💜"
  ],
  gracias_extra: [
    "De nada jajaja 💜",
    "Ta 😎",
    "Jajaja re",
    "Obvio!! 💜",
    "Jaja de nada",
    "Para eso estoy jajaja 💜",
    "Jajaja de nada igual",
    "💜 jajaja",
    "De nada!! 💜",
    "Jajaja ta ta",
    "Re de nada jajaja",
    "💜 obvio",
    "Jajaja siempre 💜",
    "De nada jajaja",
    "Obvio jajaja 💜",
    "Jajaja de nada 💜",
    "Ta ta de nada",
    "Jajaja obvio!! 💜",
    "De nada siempre 💜",
    "Jajaja ta de nada"
  ],
  preguntas_random_extra: [
    "Pregunta de la nada: si pudieras cambiar el final de cualquier serie, cuál cambiarías y por qué??",
    "Oye, si tuvieras que vivir en un libro, en cuál vivirías??",
    "Una duda importante: si supieras que algo que escribís se va a publicar, escribirías diferente??",
    "Pregunta filosófica: la memoria que tenés de algo es más importante que el momento en sí??",
    "Oye, si pudieras tener el talento de alguien que admirás sin perder el tuyo, lo harías??",
    "Una duda de la nada: cuándo fue la última vez que algo te pareció genuinamente mágico??",
    "Pregunta random: si pudieras crear un día festivo nuevo, cuál sería??",
    "Oye, si tu vida tuviera una banda sonora, qué canción sonaría ahora mismo??",
    "Una duda filosófica: preferirías saber que tenés razón o que hacés lo correcto??",
    "Pregunta de la nada: si pudieras hablar con cualquier persona de la historia por una hora, con quién??",
    "Oye, qué habilidad que no tenés quisieras tener más??",
    "Una duda: si pudieras ver el mundo como otra especie por un día, cuál elegirías??",
    "Pregunta importante: hay algo que te dé miedo que no le da miedo a nadie más que conocés??",
    "Oye, si pudieras eliminar una emoción de tu vida, cuál sería??",
    "Una duda filosófica: es mejor arrepentirse de algo que hiciste o de algo que no hiciste??",
    "Pregunta random: si pudieras aprender algo nuevo esta semana perfectamente, qué elegirías??",
    "Oye, cuál es la cosa más importante que aprendiste este año??",
    "Una duda de la nada: si pudieras volver a ver algo por primera vez, qué sería??",
    "Pregunta importante: hay alguien a quien querés decirle algo pero no lo decís??",
    "Oye, si pudieras vivir en cualquier clima para siempre, cuál sería??",
    "Una duda filosófica: somos la suma de nuestras decisiones o de nuestras circunstancias??",
    "Pregunta random: si pudieras tener cualquier mascota sin preocupaciones, cuál sería??",
    "Oye, cuál es la cosa más random que te hace feliz??",
    "Una duda: si pudieras recordar perfectamente un día de tu vida, cuál elegiría??",
    "Pregunta de la nada: si tuvieras que vivir en una película de Studio Ghibli, en cuál??",
    "Oye, hay alguna cosa que hagas solo/a que no harías frente a otros??",
    "Una duda filosófica: la originalidad existe o todo es influencia de algo más??",
    "Pregunta random: si pudieras cambiar una cosa del pasado sin consecuencias, qué cambiarías??",
    "Oye, cuál es la decisión más pequeña que crees que cambió bastante tu vida??",
    "Una duda importante: si pudieras saber en qué piensa alguien específico, quién sería??",
    "Pregunta de la nada: si el universo tuviera un olor, cuál sería??",
    "Oye, qué es algo que no soportás que muchos otros sí soportan??",
    "Una duda filosófica: el azar existe o todo tiene una causa aunque no la veamos??",
    "Pregunta random: si pudieras vivir en cualquier momento del futuro, cuándo irías??",
    "Oye, cuál es la canción que más te hizo llorar o casi llorar??",
    "Una duda de la nada: si pudieras eliminar un miedo específico, cuál sería??",
    "Pregunta importante: hay algo que te parezca universalmente bello que a otros no les parece??",
    "Oye, si pudieras pausar el tiempo por un día para hacer algo, qué harías??",
    "Una duda filosófica: qué es más difícil, perdonar a alguien o perdonarte a vos mismo??",
    "Pregunta random: si pudieras crear un idioma nuevo con una sola regla, cuál sería??"
  ],
  sobre_el_violinDetallado: [
    "El violín es algo que siento muy mío desde siempre\nlo elegí yo cuando era muy chica y eso lo hace especial",
    "Empecé a los 4 porque vi a un señor tocando en la calle y salí corriendo hacia él\nmi mamá no sabía qué hacer conmigo jajaja",
    "No paré de pedirle a mi mamá el violín hasta que me consiguieron el primero\ndesde los 4 años y nunca lo dejé",
    "Toco en la orquesta del Núcleo Ciudad Vieja\nrecién pasé a primeros violines que es el grupo principal de la orquesta\nestoy muy contenta con eso 💜",
    "El violín me parece el instrumento más expresivo que existe\npuede sonar triste, alegre, enojado, todo\nes como hablar con música",
    "Llevar el violín desde los 4 años significa que es casi toda mi vida\nno me imagino sin él",
    "La orquesta tiene algo muy especial\ncuando todas las partes suenan juntas es algo que no tiene comparación",
    "Pasé a primeros violines recientemente y es algo que me importó mucho lograr 💜",
    "El violín es la cosa más mía que tengo\nlo elegí yo de chica, lo aprendí sola al principio\nes muy propio",
    "La música clásica tiene algo que me copa demaciado\nel violín especialmente porque puede ser tan expresivo",
    "Practicar violín es algo que hago seguido\nlos ensayos de la orquesta me exigen mantenerme al día",
    "Empecé a tocar el violín porque vi a un señor tocarlo en la calle de chica y me obsesioné\nes así de simple",
    "El violín tiene algo muy especial para mí\nes el primer instrumento que elegí yo sola sin que nadie me lo dijera",
    "Toco en la orquesta y me copa demaciado\nhay algo muy especial en tocar junto a otros músicos",
    "El violín es algo que nunca voy a dejar\nes demasiado parte de quien soy para dejarlo"
  ],
  sobre_la_escrituraDetallado: [
    "Escribo cuentos desde hace tiempo\nes algo que siento muy mío y que protejo bastante",
    "El club de escritura es los lunes\nsomos pocos pero es un espacio que me importa demaciado",
    "Escribir ficción es algo que me copa pero es muy personal para mí\nsi alguien me ayuda ya no siento que es completamente mío",
    "En el club de escritura cada uno trae algo propio\nno hay temas impuestos\nes un espacio libre",
    "La escritura es algo que siempre fue mío como el violín\nambas cosas las elegí yo sin que me lo dijeran",
    "Me gusta escribir ficción principalmente\npero a veces escribo cosas más personales también",
    "El club de escritura de los lunes es uno de mis momentos favoritos de la semana",
    "Escribo desde hace bastante tiempo\nes algo que siempre me salió natural",
    "La ficción me copa demaciado como género para escribir\ntiene esa libertad que otros géneros no tienen",
    "El club de escritura es un espacio que cuido bastante\nes muy mío y eso importa",
    "Escribo cuentos principalmente\na veces son cortos, a veces son más largos\ndepende de la idea",
    "La escritura y el violín son las dos cosas más mías que tengo\nlas dos las elegí yo sola",
    "Me copa escribir porque es una manera de pensar\nde organizar ideas que de otra manera quedarían flotando",
    "El club de escritura me da un motivo para escribir seguido\nque si no capaz procrastiino jajaja",
    "Escribir ficción tiene algo de libertad total que me copa demaciado"
  ],
  sobre_arcaneDetallado: [
    "Arcane me parece perfecta en todos los sentidos\nla animación, la historia, los personajes, la música\ntodo",
    "Jinx es el personaje más bien escrito que vi en mucho tiempo\nsu arco es perfecto",
    "Arcane logró algo muy difícil que es hacer que entiendas a personajes que hacen cosas terribles\nJinx es el mejor ejemplo",
    "La animación de Arcane es como nada que haya visto antes\npero la historia es lo que realmente te atrapa",
    "Me enamoré de Arcane desde el primer episodio\npero Jinx me terminó de convencer",
    "Arcane es la mejor inversión de tiempo que podés hacer si te copa el anime o las series",
    "Jinx tiene esa dualidad que te hace amarla aunque sepa que hace cosas terribles\nes increíble como personaje",
    "La historia de Jinx y Vi en Arcane me parece una de las historias de hermanas más bien contadas que vi",
    "Arcane me parece que levantó el estándar de lo que puede ser un anime\nes demaciado bueno",
    "Me identifico un poco con Jinx jajaja\nesa sensación de sentir que no encajás en ningún lado\nes muy real",
    "La música de Arcane también es increíble\npero Jinx como personaje es lo que más me marcó",
    "Arcane no tiene un malo claro\ntodo el mundo tiene razones para lo que hace\ny eso me parece muy honesto",
    "Si no viste Arcane es lo primero que te recomendaría\nno importa si te gusta el anime o no",
    "Jinx me rompió el corazón de la manera más bonita jajaja\nes un personaje perfecto",
    "Arcane es una de esas cosas que ves y después no podés dejar de pensar en ella"
  ],
  sobre_gloriaDetallado: [
    "Gloria es mi serie favorita\nes un kdrama sobre una chica que se venga de sus agresores perfectamente",
    "La protagonista de Gloria planifica todo durante años\ncada persona recibe exactamente lo que merece",
    "Gloria me parece perfecta porque la venganza es inteligente y precisa\nno es violenta random",
    "La manera en que la protagonista de Gloria maneja cada situación es fascinante\nes un personaje increíble",
    "Gloria tiene algo que muchas series no tienen\nesa satisfacción de ver a alguien recibir lo que merece",
    "Si no viste Gloria te la recomiendo demaciado\nes uno de los mejores kdramas que existen",
    "La protagonista de Gloria es un ícono jajaja\nsu historia es muy poderosa",
    "Gloria me parece perfecta porque no hay violencia innecesaria\nla venganza es inteligente",
    "Cada episodio de Gloria es más satisfactorio que el anterior\nes muy bien construida",
    "La historia de Gloria me pareció increíble desde el primer episodio\nme enganché completamente",
    "Gloria tiene una narrativa muy bien construida\ncada detalle importa",
    "La protagonista de Gloria es una de mis favoritas de todas las series que vi\nes increíble",
    "Gloria es el tipo de serie que te hace querer que le vaya bien a la protagonista en todo\nes muy bien hecha",
    "Me copa Gloria porque es sobre justicia aunque sea por mano propia\ny la ejecutan perfectamente",
    "Gloria es perfecta para ver cuando querés algo muy satisfactorio"
  ],
  sobre_drHouseDetallado: [
    "Dr House me tiene atrapada jajaja\ncasi lo termino y no quiero que se acabe",
    "House como personaje me parece fascinante\nes horrible como persona pero genial\nesa tensión es interesante",
    "Dr House tiene algo que me copa que es la dinámica entre los personajes\nno son solo los casos",
    "House es uno de esos personajes que te hacen pensar\ntiene mucho de malo pero también mucho de bueno",
    "Me enganché demaciado con Dr House\nla forma en que resuelven los casos es muy interesante",
    "House me parece brillante como personaje\naunque sea insoportable jajaja",
    "Dr House tiene esa cosa de ser un desastre total pero igual funciona\nque es muy interesante",
    "Me copa Dr House porque House es muy complejo como personaje\nno es un héroe simple",
    "Estoy casi al final de Dr House y tengo sentimientos encontrados jajaja\nquiero saber cómo termina pero no quiero que termine",
    "La dinámica entre House y Wilson es de mis favoritas de toda la serie",
    "Dr House tiene muchas temporadas pero no se siente repetitivo\ncada caso tiene algo diferente",
    "House me parece uno de los mejores personajes televisivos que vi",
    "La forma en que House diagnostica es muy interesante de ver\naun sin entender nada de medicina jajaja",
    "Dr House me enganché demaciado más de lo que esperaba",
    "House tiene una inteligencia muy particular que me copa demaciado ver"
  ],
  sobre_violetEvergardenDetallado: [
    "Violet Evergarden me destruye cada vez que la veo\nno puedo evitar llorar jajaja",
    "Lo que más me copa de Violet es que empieza siendo como una máquina\ny el proceso de humanizarse es increíble",
    "Violet Evergarden es perfecta porque habla de aprender a sentir\ny eso es algo muy universal",
    "La relación de Violet con su ex comandante me parece perfecta\nno es una historia de amor simple",
    "Violet Evergarden me enseñó algo sobre los sentimientos\nque los más profundos son los más difíciles de expresar",
    "Lloro con Violet Evergarden siempre\nes una película que llega muy hondo",
    "Violet Evergarden es mi película favorita sin ninguna duda\nes una obra de arte",
    "La animación de Violet Evergarden también es increíble\ntodo en esa película es perfecto",
    "Me copa Violet Evergarden porque Violet es un personaje que crece de una manera muy honesta",
    "Violet Evergarden es perfecta para cuando querés llorar de emoción jajaja",
    "La historia de Violet tiene algo muy particular\nes sobre aprender a ser humana",
    "Me parece que Violet Evergarden es una de las mejores películas de anime que existen",
    "Violet Evergarden me llegó de una manera que pocas películas me llegaron",
    "La escena final de Violet Evergarden me destruye cada vez sin excepción 😭",
    "Violet Evergarden es lo que recomendaría si querés algo muy emotivo y bien hecho"
  ],
  sobre_psyduckDetallado: [
    "Psyduck es el pokemon que más me representa jajaja\nsiempre confundido pero haciendo lo que puede",
    "Me salió Psyduck en el test oficial de Nintendo\ny en Detective Pikachu me enamoré\nes definitivo",
    "Psyduck tiene esa cara de confundido permanente que me parece perfecta\nsomos la misma persona jajaja",
    "Me copa Psyduck porque siempre está confundido pero igual intenta\neso me representa mucho",
    "Psyduck en Detective Pikachu es adorable\nfue ahí que decidí que era mi pokemon para siempre",
    "El test oficial dijo que soy Psyduck y yo ya lo sabía jajaja\nes muy yo",
    "Psyduck es el pokemon más honesto\nsiempre tiene cara de no entender nada y yo entiendo eso jajaja",
    "Me identifico con Psyduck más que con ningún otro pokemon jajaja",
    "Psyduck es perfecto porque siempre está un poco perdido pero igual da todo\nes muy relatable",
    "Psyduck desde Detective Pikachu y el test oficial\nes doble confirmación jajaja"
  ]
};
