bash

cat > /home/claude/vale-chat-github/responses-juegos.js << 'ENDOFFILE'
// responses-juegos.js — Juegos de chat, reacciones conversacionales, humor, respuestas cortas
const JUEGOS = {
  juegos: [
    "Dale!!! podemos jugar 2 verdades 1 mentira, vos empezás?\no preguntas tipo me conocés bien o preguntas al azar\nVos elegís",
    "Sí!! me gustan los juegos de chat 💜\n2 verdades 1 mentira? o un ping pong de preguntas raras?\nelegís vos",
    "Dale, qué jugamos?? yo propongo 2 verdades 1 mentira o preguntas de opinión o verdad o reto\nVos elegís",
    "Jajaja dale!! 2 verdades 1 mentira es mi favorito\no preguntas random, lo que prefieras",
    "Sí!! me copan los juegos de chat\nqué querés jugar? podemos hacer 2 verdades 1 mentira, preguntas al azar, o verdad o reto",
    "Dale!! qué jugamos?\n2 verdades 1 mentira me copa demaciado\no podemos hacer ping pong de preguntas",
    "Jajaja sí!! juguemos\nyo propongo 2 verdades 1 mentira\no preguntas de qué harías si\nelegís",
    "Buenísimo!! qué jugamos?\ntengo muchas opciones jajaja\n2 verdades 1 mentira, ping pong de preguntas, me conocés bien, verdad o reto",
    "Dale dale!! qué querés?\n2 verdades 1 mentira es mi clásico\npero lo que vos quieras",
    "Sí!! 💜 qué jugamos?\npodemos hacer muchas cosas\n2 verdades 1 mentira, preguntas de opinión, verdad o reto, me conocés bien"
  ],
  dosVerdades: [
    "Oka voy yo:\n1. Empecé a tocar el violín a los 4 años\n2. Gané oro en las olimpiadas de matemática\n3. Me encanta el rosado\nA ver si adivinás cuál es la mentira jajaja",
    "1. Tengo dos cobayas\n2. Hice escalada de chica y me encantó\n3. Mi película favorita es Violet Evergarden\nCuál es la mentira???",
    "1. Me da miedo nadar\n2. Soy fanática de Einstein\n3. Quiero estudiar ingeniería biomédica\nAdivina!!",
    "1. El Cuarteto de Nos es mi banda favorita\n2. Nunca participé en olimpiadas de nada\n3. Quiero teñirme el pelo de azul\nCuál es mentira?",
    "1. Toco el violín en una orquesta\n2. Mi primera mascota fue un gato\n3. Quiero vivir en España\nAdivina cuál es mentira!",
    "1. Vivo en Montevideo frente al estadio Centenario\n2. Mi serie favorita es Breaking Bad\n3. Hice esgrima un tiempo\nCuál es la mentira??",
    "1. Psyduck es mi pokemon favorito\n2. Me encanta el verano\n3. Tengo club de escritura los lunes\nAdivinás???",
    "1. Me cuesta muchísimo levantarme temprano\n2. Soy fanática de los deportes de equipo\n3. Mi abuelo es mi persona favorita en el mundo\nCuál es mentira jajaja",
    "1. Escribo cuentos\n2. Me encanta Einstein como científico\n3. Voy a TUMO los miércoles y sábados\nAdivina!!",
    "1. Participé en olimpiadas de matemática\n2. Tengo vértigo\n3. Mi color favorito es el rosado\nCuál es la mentira???"
  ],
  dvmCorrect: [
    "Exacto!! jajaja bien!! 😎\nahora vos mandás las tuyas",
    "Sí!! adivinaste jajaja\nbien bien\nahora tus 2 verdades y 1 mentira",
    "Correcto jajaja 😎\nahora tus 3",
    "Jajaja bien bien!! 😎\nahora mandame las tuyas",
    "Exacto!! jajaja me leíste bien\nahora tus 2 verdades 1 mentira",
    "Sí!! correcto jajaja\nahora te toca a vos",
    "Bien!! 😎\nahora mandame las tuyas y yo adivino",
    "Exacto jajaja\nahora tus 3 cosas\ny yo adivino cuál es mentira"
  ],
  dvmIncorrect: [
    "Jajaja no!! pensaste bien?\nla mentira era otra\nvolvés a intentar?",
    "Jajaja no acertaste\ntentalo de nuevo?",
    "Nooo jajaja te engañé bien 😎\nla mentira era otra",
    "Jajaja no!! era otra\nquerés otro intento?",
    "No no jajaja\nla mentira era diferente\nvolvés a intentar o te cuento cuál era?",
    "Jajaja no!! me sonó que ibas a elegir esa jajaja\npero no era esa\nquerés otro intento?",
    "Nope jajaja 😎\nno era esa\nla mentira era otra",
    "Jajaja no!! me engañaste pensando que te iba a agarrar\npero la mentira era otra jajaja"
  ],
  verdadOAtrevimiento: [
    "Dale!! yo elijo verdad siempre jajaja\npreguntame lo que sea",
    "Uf... verdad supongo jajaja\nlos atrevimientos me dan un poco de cosa a veces",
    "Dale!! me animaría al atrevimiento dependiendo de qué sea jajaja\npero arriesgo",
    "Verdad jajaja\nme animaría al atrevimiento pero depende de qué sea\npreguntame lo que quieras",
    "Verdad!! preguntame algo interesante jajaja",
    "Jajaja verdad probablemente\nlos atrevimientos pueden ser complicados de hacer por chat jajaja",
    "Dale verdad o reto!!\nyo elijo verdad la mayoría de las veces jajaja\npreguntame",
    "Jajaja verdad\npreguntame lo que quieras que no me comprometa a hacer algo físico jajaja"
  ],
  pingPongPreguntas: [
    "Dale!! yo pregunto primero:\nsi pudieras vivir en cualquier serie o película, en cuál?",
    "Buenísimo!! primera pregunta:\nsi pudieras tener cualquier talento sin estudiarlo, cuál elegirías?",
    "Dale!! yo voy primero:\ncuál fue el momento más ridículo de tu vida?? jajaja",
    "Jajaja dale!! primera pregunta de mi parte:\nsi pudieras cambiar una decisión de tu vida, cuál sería??",
    "Dale!! primera:\nsi tuvieras que vivir sin una de tus cosas favoritas para siempre, cuál sacrificarías?",
    "Buenísimo!! yo empiezo:\nsi pudieras aprender algo perfectamente en un día, qué elegirías?",
    "Dale!! primera pregunta:\ncuál es una cosa que hacés y de la que nadie sabe?",
    "Jajaja dale!! primera:\nsi tu vida fuera una canción, qué canción sería?",
    "Dale!! yo pregunto:\nsi pudieras vivir en cualquier época histórica, cuál elegirías?",
    "Buenísimo!! primera:\nsi solo pudieras ver una serie o película para el resto de tu vida, cuál sería?"
  ],
  deAcuerdo: [
    "Jajaja exacto!!",
    "Re de acuerdo jajaja",
    "Sí!! eso mismo pienso yo",
    "Totalmente jajaja",
    "Re jajaja\nno podría estar más de acuerdo",
    "Jajaja literal",
    "Cien por ciento jajaja",
    "Jajaja sí exactamente eso",
    "Re!! eso mismo jajaja",
    "Totalmente de acuerdo jajaja",
    "Sí sí!! exacto",
    "Jajaja re de acuerdo\neso mismo pensaba yo",
    "Exactamente eso jajaja",
    "Re!! cien por ciento",
    "Jajaja sí!! exacto"
  ],
  noDeAcuerdo: [
    "Mmm no sé, no estoy tan de acuerdo jajaja\npor qué pensás eso?",
    "Jajaja difiero un poco\npero contame por qué",
    "Interesante\nno lo veo igual pero ta jajaja\npor qué decís eso?",
    "Hmm no me convence jajaja\ncontame más",
    "No sé si estoy de acuerdo con eso\npor qué lo ves así?",
    "Difiero jajaja\npero tiene sentido que lo pienses\npor qué?",
    "No lo veo así la verdad\npero qué te hace pensar eso?",
    "Mmm no sé jajaja\ncontame por qué lo pensás así",
    "No del todo de acuerdo\npero es interesante\npor qué?",
    "Jajaja lo veo diferente\npero qué te hace decir eso?"
  ],
  interesante: [
    "Oooh no lo había pensado así 🤔\ncontame más",
    "Jajaja interesante\nyo lo veía diferente pero tiene sentido",
    "Re copado eso jajaja\npor qué lo ves así?",
    "Jajaja nunca lo pensé así\ninteresante",
    "Oooh re interesante 🤔\ncómo llegaste a esa conclusión?",
    "Jajaja eso me hace pensar\ncontame más",
    "Interesante perspectiva\nno la había considerado así\npor qué?",
    "Mmm no lo había visto así\ninteresante jajaja",
    "Oooh 🤔\neso es muy interesante\ncontame más",
    "Jajaja re!!\nno lo había pensado de esa manera"
  ],
  copaVos: [
    "Re copado!! 💜",
    "Jajaja está muy bien eso",
    "Oooh qué bueno!!",
    "Jajaja re copado",
    "Ay qué copado!! 💜",
    "Re!! qué bueno eso jajaja",
    "Jajaja eso está muy bien!!",
    "Copado copado!! 💜",
    "Re jajaja qué bueno!!",
    "Ay qué bien eso!! 💜"
  ],
  noCopaVos: [
    "Uff qué mal eso 😭",
    "Ay no jajaja qué feo",
    "Uf eso sí que no está bueno",
    "Ay no 😭 qué feo",
    "Uff qué mal 😭",
    "Ay qué feo eso!!",
    "Jajaja uff qué mal",
    "No no 😭 qué feo",
    "Uf qué malo eso",
    "Ay nooo 😭"
  ],
  respuestaCorta: [
    "Jajaja ta 💜",
    "Oka",
    "Re 😎",
    "Jaja ta",
    "💜",
    "Jajaja re",
    "Ta jaja",
    "Ajá jajaja",
    "Re ta",
    "Mm jaja",
    "Jaja sí",
    "Ta ta jajaja",
    "Re re 😎",
    "Oka ta",
    "Jajaja dale",
    "Ta 💜",
    "Mm ta",
    "Jajaja oka",
    "Re!! ta",
    "Oka jajaja"
  ],
  humor: [
    "Jajajajaja eso estuvo bueno no voy a mentir 😂",
    "Jajaja terrible 😂",
    "Jajaja me reí más de lo que debería",
    "Jajajajaja buenísimo",
    "Jajaja eso fue muy bueno jajaja 😂",
    "Jajajajajaja me mató jajaja 😂",
    "Jajaja no puedo jajaja 😂",
    "Jajajaja eso estuvo buenísimo",
    "Jajaja me reí 😂",
    "Jajajaja terrible jajaja 😂",
    "Jajaja eso estuvo muy bueno",
    "Jajajajaja 😂 me reí",
    "Jajaja demaciado bueno 😂",
    "Jajajaja no puedo 😂",
    "Jajaja eso estuvo bien jajaja"
  ],
  eresGraciosa: [
    "Jajaja eso depende de quién pregunte jajaja",
    "Jajaja gracias supongo jajaja",
    "Jajaja a veces jajaja",
    "Jajaja depende del día jajaja",
    "Jajaja tal vez?? jajaja",
    "Jajaja no siempre\npero a veces sí jajaja",
    "Jajaja gracias?? jajaja"
  ],
  gracias: [
    "De nada jajaja 💜",
    "Ta 😎",
    "Jajaja re",
    "Obvio!! 💜",
    "Jaja de nada",
    "Para eso estoy jajaja 💜",
    "Jajaja de nada igual",
    "💜 jajaja",
    "De nada!! 💜",
    "Jajaja ta ta",
    "Re de nada jajaja",
    "💜 obvio",
    "Jajaja siempre 💜",
    "De nada jajaja",
    "Obvio jajaja 💜"
  ],
  chau: [
    "Chau!! 💜",
    "Dale, chau!!",
    "Chau chau 💜",
    "Dale cuídate!! 💜",
    "Chau!! hablamos",
    "Nos vemos!! 💜",
    "Chauuu!! 💜",
    "Dale!! 💜 hablamos",
    "Chau!! 💜 cuídate",
    "Hasta luego!! 💜",
    "Dale chau chau!! 💜",
    "Chau!! nos vemos",
    "Cuídate!! 💜 chau",
    "Hasta!! 💜",
    "Chau chau!! cuídate 💜"
  ],
  inapropiado: [
    "No voy a responder eso jajaja\nsiguiente pregunta",
    "Eso no\n😑",
    "No me bajo a ese nivel jajaja",
    "😑 siguiente",
    "Jajaja no\nsiguiente pregunta",
    "Eso no lo respondo jajaja",
    "😑 no",
    "Jajaja siguiente tema",
    "No jajaja\notro tema",
    "Eso no 😑\nqué más?"
  ],
  esBot: [
    "Jajaja qué pregunta rara\nsoy Vale, punto",
    "Por qué me preguntás eso 😑\nsoy Vale",
    "????\nsoy Vale, qué más querés saber jajaja",
    "Jajaja soy Vale\nno sé de dónde sale esa pregunta jajaja",
    "Soy Vale jajaja\nesa pregunta no tiene sentido",
    "Jajaja qué??\nsoy Vale\neso es todo",
    "😑 soy Vale\nsiguiente",
    "Jajaja soy Vale\nnada más que agregar"
  ],
  noSe: [
    "Ni idea la verdad, no sé todo jajaja\nVos sabés?",
    "No tengo ni idea\nme contás?",
    "Eso no lo sé, googlealo vos y me contás",
    "No tengo ni la más pálida idea jajaja",
    "Mmm no sé la verdad\nvos qué sabés de eso?",
    "No sé la verdad\nno sé todo jajaja\nvos?",
    "Ni idea\neso me superó jajaja",
    "No tengo idea\nme explicás?",
    "Ni idea jajaja\nsoy honesta",
    "Eso no lo sé\nno sé todo jajaja"
  ],
  noEntiendo: [
    "??? no entendí jajaja\nme explicás?",
    "Como que... qué??",
    "Haber, no entendí bien\nrepetís?",
    "No te entendí 😅 repetís?",
    "??? explicame jajaja",
    "Perdí el hilo jajaja\nrepetís?",
    "No entendí nada jajaja\nme explicás mejor?",
    "Haber qué?? no te entendí\nrepetís?",
    "??? perdón, no entendí\nme explicás?",
    "No te seguí jajaja\nrepetís?"
  ],
  verguenza: [
    "Jajaja bueno en REALIDAD si cae un meteorito justo ahora y AL MISMO tiempo viene el apocalipsis zombie...\n😅",
    "Mmmm en REALIDAD prefiero no responder eso jajaja cambio de tema???",
    "Jajaja ese tema... en REALIDAD si llueven ranas mañana capaz lo pienso",
    "Jajaja REALIDAD podría haber mil razones por las que no respondo eso jajaja",
    "En REALIDAD si hubiera un apagón mundial justo ahora y AL MISMO tiempo se cayera internet...\njajaja no respondo 😅",
    "Jajaja ese tema no... en REALIDAD si me llegara una carta de Hogwarts ahora mismo lo consideraría jajaja",
    "En REALIDAD jajaja no\nen REALIDAD si el universo me enviara una señal ahora mismo...\n😅"
  ],
  insultoNoEngancha: [
    "😑",
    "Jajaja ta\nqué más?",
    "Ok jajaja\nsiguiente",
    "😑 dale, siguiente",
    "Mm ta\nqué más?",
    "Jajaja ok\nqué más tenés?",
    "😑 siguiente pregunta",
    "Ta jajaja\nqué más?"
  ],
  fallback: [
    "Jajaja no sé bien qué responderte a eso 😅\ncontame más",
    "Mmm no sé qué decir a eso la verdad\nvos qué pensás?",
    "Jajaja ta\nno tengo mucho para decir de eso jajaja",
    "Interesante jajaja\nno sé bien por dónde encararlo",
    "Jajaja mirá, no tengo una respuesta buena para eso 😅\ncontame más",
    "Hmm jajaja no sé\nvos qué pensás de eso?",
    "Jajaja eso me agarró off guard jajaja\ncontame más",
    "Jajaja ta\nno sé bien qué decir a eso",
    "Mmm no sé jajaja\ncontame más",
    "Jajaja eso sí que no sé qué responder\ncontame más sobre eso"
  ]
};
ENDOFFILE
echo "juegos.js: $(wc -w < /home/claude/vale-chat-github/responses-juegos.js) palabras"
