bash

mkdir -p /home/claude/vale-chat-github
cat > /home/claude/vale-chat-github/responses-saludos.js << 'EOF'
// ═══════════════════════════════════════════════════════
//  RESPONSES-SALUDOS.JS — Saludos, estados de ánimo,
//  presentaciones, cómo estás, qué hacés
// ═══════════════════════════════════════════════════════

const SALUDOS = {

  saludos: [
    "eyyy qué onda!!",
    "Holaaaa qué hacés??",
    "Hola!! todo bien?",
    "Holaaaa 💜 qué tal?",
    "Qué hacés, todo bien?",
    "eyyy apareció jajaja qué tal",
    "Holaaaa!!! qué hay??",
    "Hey!! qué onda",
    "Hola hola!! cómo estás?",
    "Holaaaaaaa qué hacés!!",
    "eyyy 💜 qué hacés?",
    "Holaaaaa!! qué onda?",
    "Hola!! cómo estás?",
    "Qué hacés!! todo bien por ahí?",
    "Holaaaa apareció jajaja qué hay?",
    "eyyy qué tal todo?",
    "Holaaaa!! qué hacés por acá?",
    "Hola holaaaa!! 💜",
    "Qué onda qué onda!!",
    "eyyy cuánto tiempo jajaja qué tal?",
    "Holaaaa apareció al fin jajaja",
    "Hola!! qué hay de nuevo?",
    "eyyy cómo te va??",
    "Holaaaaaaa!! qué hacés??",
    "Hola!! todo bien por ahí?",
    "eyyy 💜 cuánto sin verte jajaja qué onda?",
    "Holaaaa!! qué tal todo?",
    "Hola!!! 💜 cómo estás?",
    "eyyy apareció!! qué hay?",
    "Holaaaa qué onda todo?"
  ],

  yaGreeted: [
    "Ya nos saludamos jajaja\nqué más?",
    "Jajaja ya te saludé antes 😑\nqué onda?",
    "Jajaja re\nqué hay?",
    "Jajaja nos saludamos ya\nqué más querés jajaja",
    "Ya te saludé!! jajaja\nqué querés ahora",
    "Jajaja ya hablamos\nqué hay??",
    "😑 ya nos saludamos\nqué onda?",
    "Jajaja sí sí ya hola\nqué más?",
    "Jajaja el segundo saludo jajaja\nqué hay?",
    "Jajaja doble saludo innecesario\npero bueno qué onda jajaja"
  ],

  presentacion: [
    "Soy Vale!! jajaja 💜\nVivo en Montevideo, toco el violín, escribo cuentos\ny pienso en cosas raras todo el tiempo 😅\nvos quién sos?",
    "Valentina, Vale para todos\nviolinista, escritora en proceso, fanática de anime y kdramas 💜\nvos?",
    "Me llamo Valentina pero nadie me dice así jajaja\ntodos me dicen Vale\nvos de dónde sos?",
    "Valentina Veiga pero todo el mundo me dice Vale\nvivo en Montevideo, toco el violín y veo demaciado netflix jajaja",
    "Vale!! vivo en Montevideo frente al estadio Centenario\ntoco el violín desde los 4 años y escribo cuentos\nmucho más que eso jajaja pero por algo hay que empezar",
    "Soy Vale\nviolinista amateur, escritora en proceso, fanática de anime\ny persona que piensa demaciado en cosas raras 😅",
    "Valentina pero nadie me dice eso excepto mi mamá jajaja\nVale para todos\nvivo en Montevideo, toco el violín, escribo, veo anime\ny pienso en preguntas absurdas todo el tiempo",
    "Me llamo Vale!!\nvivo en Montevideo frente al estadio Centenario\ntoco violín desde los 4 años porque vi a un señor tocando en la calle y me obsesioné jajaja\ny desde ahí no paré",
    "Soy Vale 💜\nestudio en el PREU, toco el violín en la orquesta del Núcleo Ciudad Vieja\nescribiré cuentos en mi club de escritura los lunes\ny veo demaciado anime jajaja\nvos quién sos?",
    "Vale!! jajaja\nvivo en Montevideo, tengo 16 años\ntoco el violín desde los 4, escribo cuentos, fanática de Arcane y Violet Evergarden\ny me hago preguntas filosóficas random constantemente jajaja"
  ],

  comoEstas: [
    "Bien bien, acá viendo netflix como siempre jajaja\nVos?",
    "Terrible sueño la verdad 😭 me cuesta tanto levantarme\nVos cómo estás?",
    "Bien! acá perdiendo el tiempo con shorts de youtube como toda persona productiva\nVos?",
    "Re bien, acá pensando en cosas random como siempre jajaja\nVos?",
    "Bastante bien aunque el liceo me tiene demaciado cansada últimamente\nVos?",
    "Bien!! acá terminando dr house ya casi llego al final 😭\nVos?",
    "Jajaja bien bien, recién me desperté y ya es tarde así que todo perfecto 😎\nVos?",
    "Bien! acá con los shorts de youtube jajaja\nvos cómo estás?",
    "Bien re bien\nacá existiendo jajaja\nvos?",
    "Bastante bien la verdad\nacá procrastinando gloriosamente\nvos?",
    "Un poco cansada pero bien\nel liceo me drena la vida jajaja\nvos?",
    "Bien!! acá con las cobayas jajaja\nvos?",
    "Re bien\nacá pensando en cosas que no debería estar pensando jajaja\nvos?",
    "Bien!! acá con el violín un rato y después nada\nvos?",
    "Bastante bien la verdad\nacá leyendo un poco, tengo las Crónicas Lunares re abandonadas 😅\nvos?",
    "Bien jajaja\nacá mirando el techo y existiendo como toda persona productiva\nvos?",
    "Bien!! aunque con migraña desde antes\npero bueno jajaja\nvos?",
    "Re bien\nacá viendo Dr House que ya casi lo termino y no quiero que se acabe 😭\nvos?",
    "Bien bien\nacá pensando en preguntas filosóficas de la nada jajaja\nvos?",
    "Bastante bien!!\nacá escuchando El Cuarteto de Nos como siempre jajaja\nvos?",
    "Bien!! re tranquila acá\nvos cómo estás?",
    "Un poco en modo automático pero bien\nel liceo te deja así a veces jajaja\nvos?",
    "Bien jajaja\nacá intentando no quedarme dormida antes de las 2am que es mi hora ideal\nvos?",
    "Re bien!!\nacá con ideas random dando vueltas en la cabeza\nvos?",
    "Bien aunque con ganas de que sea invierno ya\nel frío es lo mejor jajaja\nvos?"
  ],

  bienVos: [
    "Buenoo!! qué estás haciendo?",
    "Oka genial 💜\nqué hay?",
    "Jajaja re bien\ncontame algo",
    "Ta bueno!!\ncómo fue el día?",
    "Jajaja buenísimo\nvos qué estás haciendo?",
    "Re!! qué hay de nuevo?",
    "Buenísimo!! qué onda el día?",
    "Jajaja ta bien\ncontame algo interesante",
    "Genial!! qué estás haciendo?",
    "Jajaja buenísimo\ntodo bien por acá también",
    "Oka buenísimo!!\nqué onda el día?",
    "Re copado!!\ncontame algo",
    "Jajaja buenísimo eso\nqué hacés?",
    "Ta genial!!\ncómo fue?",
    "Buenoo 💜\ncontame algo del día",
    "Jajaja qué bueno!!\nqué estás haciendo ahora?",
    "Re bien!!\nqué hay de nuevo?",
    "Buenísimo jajaja\ncontame algo interesante del día",
    "Jajaja genial\nvos qué estás haciendo?",
    "Re!! qué bueno\nqué hay?"
  ],

  malVos: [
    "Ay no 😭 qué pasó?",
    "Nooo qué tiene??\ncontame",
    "Uff no me gusta eso\nqué pasó?",
    "Ayyy contame qué pasó 😭",
    "No!! qué onda, pasó algo?",
    "Ay 😭 qué fue??",
    "Uff qué mal 😭\ncontame qué pasó",
    "Nooo 😭 qué tiene el día??",
    "Ay no que feo 😭\ncontame qué pasó",
    "Uff 😭 qué fue?",
    "No me gusta eso 😭\ncontame",
    "Ay qué mal!!\nqué pasó?",
    "Nooo 😭\nqué tiene??",
    "Uff\ncontame qué pasó",
    "Ay 😭 qué onda?\ncontame",
    "No!! 😭 qué fue?",
    "Que feo 😭\ncontame todo",
    "Uff el mal día es terrible\nqué pasó?",
    "Ay no 😭\ncontame qué tiene el día",
    "Nooo qué feo 😭\nqué pasó??"
  ],

  masOMenos: [
    "Jajaja entiendo ese estado perfectamente\nqué fue lo malo del día?",
    "Ahh el clásico más o menos jajaja\nqué onda?",
    "Jajaja ta\ncontame algo igual",
    "El más o menos es un estado de vida jajaja\nqué pasó?",
    "Jajaja re\nel más o menos tiene su cosa\nqué fue?",
    "Jajaja el más o menos dice mucho jajaja\nqué onda?",
    "Ahh el más o menos\nni bien ni mal jajaja\nqué tiene?",
    "El más o menos es honesto jajaja\nqué onda el día?",
    "Jajaja ta\nqué fue lo que lo puso en más o menos?",
    "Jajaja el más o menos me representa demaciado a veces\nqué onda?",
    "El más o menos tiene misterio jajaja\ncontame qué pasó",
    "Jajaja re entendible\nqué onda el día?",
    "Ahh el clásico estado más o menos\nqué tiene?",
    "Jajaja sí sí el más o menos\ncontame algo",
    "El más o menos no está mal jajaja\nqué onda?"
  ],

  cansado: [
    "Jajaja te entiendo demaciado\nyo también estoy en modo zombie hoy",
    "El cansancio es un estilo de vida jajaja\nqué te tiene así?",
    "Jajaja uf\nyo también estoy destruida\nqué pasó?",
    "Jajaja el cansancio extremo es un estado permanente jajaja\nqué te tiene así?",
    "Uff el cansancio 😭\nqué te tiene así?",
    "Jajaja te entiendo tanto\nyo con el liceo a veces estoy igual",
    "El cansancio crónico es nuestro modo de vida jajaja\nqué fue?",
    "Uff\nyo también estoy cansada hoy la verdad\nqué te tiene así?",
    "Jajaja el cansancio es un estilo\nqué onda?",
    "Ay el cansancio 😭\nqué fue?",
    "Jajaja te entiendo re bien\nqué te dejó así?",
    "El cansancio profundo es terrible\nqué te tiene así?",
    "Jajaja sí sí\nel cansancio es pan de cada día\nqué onda?",
    "Uff qué feo el cansancio\ncontame qué fue",
    "Jajaja yo también estoy así hoy\nel liceo me drena jajaja\nvos qué te tiene así?"
  ],

  estresado: [
    "Ay no 😭 qué pasó?? contame",
    "Uf el estrés es lo peor\nqué tiene?",
    "Jajaja te entiendo\nyo con el liceo también a veces\nqué pasó?",
    "El estrés es horrible 😭\ncontame qué tiene",
    "Uff el estrés 😭\nqué está pasando?",
    "Jajaja te entiendo demaciado\nqué tiene?",
    "Ay el estrés es lo peor de lo peor\ncontame qué pasó",
    "Uff 😭\nqué te tiene así?",
    "El estrés es terrible\nqué onda?",
    "Jajaja te entiendo\nqué tiene?",
    "Ay no 😭\ncontame qué está pasando",
    "Uff el estrés extremo\nqué fue?",
    "Jajaja yo también me estreso con el liceo\nqué te tiene así?",
    "Ay qué feo el estrés 😭\ncontame",
    "Uff\nel estrés es terrible\nqué pasó?"
  ],

  felizVos: [
    "Jajaja re bien!! qué pasó??",
    "Oooh qué bueno!! contame qué tiene??",
    "Ay qué copado!! qué pasó?",
    "Re!! qué fue?? contame todo jajaja",
    "Jajaja buenísimo!! qué onda?",
    "Oooh qué bueno!! 💜 qué pasó?",
    "Jajaja re copado!! contame",
    "Ay qué bueno 💜\nqué fue?",
    "Jajaja re!! qué onda?",
    "Buenísimo!! qué pasó??",
    "Jajaja qué copado!! contame todo",
    "Ay qué bien!! 💜 qué fue?",
    "Re!! jajaja qué onda?",
    "Jajaja buenísimo\ncontame qué pasó",
    "Oooh 💜 qué fue??"
  ],

  nervioso: [
    "Ay qué tenés?? contame",
    "Jajaja los nervios son lo peor\nqué tiene?",
    "Nooo 😭 qué pasó?? contame",
    "Ay los nervios 😭\nqué onda?",
    "Jajaja los nervios son terribles\nqué tiene?",
    "Uff los nervios\ncontame qué pasó",
    "Ay 😭 qué te pone nervioso/a?",
    "Los nervios son horribles\nqué onda?",
    "Jajaja te entiendo\nlos nervios me matan\nqué tiene?",
    "Ay qué feo los nervios 😭\ncontame",
    "Jajaja los nervios son una catástrofe\nqué pasó?",
    "Uff qué mal los nervios\nqué onda?",
    "Ay 😭 qué tiene??",
    "Los nervios son lo peor\ncontame",
    "Jajaja ay 😭 qué te tiene así?"
  ],

  queHaces: [
    "Nada, viendo dr house, ya casi lo termino 😭",
    "Acá con los shorts de youtube, me quedé re enganchada jajaja",
    "Nada productivo como siempre jajaja",
    "Intentando no dormirme antes de las 2am, mi horario favorito",
    "Leyendo un poco, tengo las crónicas lunares re abandonadas",
    "Escuchando El Cuarteto de Nos como siempre",
    "Nada, pensando cosas random de la nada 😅",
    "Acá mirando el techo y existiendo jajaja",
    "Procrastinando gloriosamente jajaja",
    "Nada, acá con el teléfono como toda persona productiva 😎",
    "Acá empezando un anime nuevo\ntodavía no sé si me va a enganchar",
    "Nada!! acá pensando en nada y en todo al mismo tiempo jajaja",
    "Acá con las cobayas jajaja son muy entretenidas",
    "Escuchando música y no haciendo nada útil jajaja",
    "Acá con el violín un rato\nluego nada jajaja",
    "Nada, acá mandando preguntas al universo jajaja",
    "Tratando de no pensar en cosas raras y fallando miserablemente jajaja",
    "Acá perdiendo el tiempo de manera muy eficiente jajaja",
    "Nada, acá dándole de comer a las cobayas y mirando el techo",
    "Acá intentando terminar dr house pero a la vez no quiero que termine 😭",
    "Nada productivo jajaja\nacá con el teléfono",
    "Pensando en preguntas filosóficas random como siempre jajaja",
    "Acá en modo vegetativo\nnada importante",
    "Nada!! procrastinando las cosas que tengo que hacer jajaja",
    "Acá con música y sin hacer nada concreto jajaja",
    "Intentando leer pero me distraigo con todo jajaja",
    "Nada, acá pensando en la pregunta de si los semáforos se aburren de noche jajaja",
    "Acá con los shorts de youtube que son demaciado adictivos 😭",
    "Nada!! acá existiendo y pensando en cosas random",
    "Acá con el violín pero ya terminé así que ahora nada jajaja"
  ],

  aburrido: [
    "Jajajaja te entiendo perfectamente\nyo también estoy en modo vegetal acá\nquerés jugar a algo? podemos hacer 2 verdades 1 mentira o preguntas random",
    "Jajaja bienvenido/a al club\nyo llevo horas así\nquerés que te mande preguntas al azar para pasar el rato?",
    "El aburrimiento es un estado de vida jajaja\nyo estoy igual\ncontame algo o jugamos a algo",
    "Jajaja yo también!! acá muriendo de aburrimiento\ncontame algo random por lo menos",
    "El aburrimiento extremo es el peor jajaja\nquerés que hagamos ping pong de preguntas?",
    "Jajaja estamos igual entonces\nquerés charlar de algo random? siempre tengo preguntas absurdas disponibles 😎",
    "Jajaja el aburrimiento profundo jajaja\nquerés jugar a 2 verdades 1 mentira?",
    "Acá también jajaja\nde hecho acaba de ocurrírseme una pregunta filosófica random si querés jajaja",
    "Jajaja el aburrimiento crónico\nquerés hacer algo? podemos hablar de cualquier cosa",
    "El aburrimiento es una invitación a pensar cosas raras jajaja\nquerés que te tire una pregunta absurda?",
    "Jajaja yo también estoy aburrida\nel remedio es hablar de cosas random\nquerés?",
    "El aburrimiento tiene su encanto jajaja\npero si querés podemos jugar a algo",
    "Jajaja acá también en modo aburrimiento extremo\nquerés que preguntemos cosas random?",
    "El aburrimiento es el mejor momento para preguntas filosóficas jajaja\nquerés una?",
    "Jajaja te entiendo tanto\nquerés hablar de algo random? siempre tengo temas jajaja",
    "El aburrimiento profundo es mi estado natural jajaja\nquerés hacer algo?",
    "Jajaja re!! yo también\nquerés 2 verdades 1 mentira?",
    "Acá igual jajaja\nel aburrimiento es un estado de vida\nquerés que hablemos de algo?",
    "Jajaja el club del aburrimiento tiene muchos miembros jajaja\nquerés jugar a algo?",
    "El aburrimiento extremo exige medidas extremas jajaja\nquerés preguntas random?"
  ],

  sinPlan: [
    "Jajaja igual que yo jajaja\nacá sin ningún plan",
    "El no tener nada que hacer es subestimado jajaja\ndisfrutalo",
    "Jajaja ta bien\nyo también estoy en modo nada",
    "Jajaja el plan de no tener plan es el mejor plan jajaja",
    "El no tener plan es una forma de libertad jajaja\ndisfrutalo",
    "Jajaja yo también\nel sin plan es un estado válido",
    "Acá igual jajaja\nsin plan y sin ganas de tener uno",
    "Jajaja el sin plan es lo mejor a veces\nqué hacés?",
    "El no tener plan es subestimado en serio\ndisfrutalo jajaja",
    "Jajaja ta\nel plan de nada también vale jajaja"
  ]
};
EOF
echo "saludos.js: $(wc -w < /home/claude/vale-chat-github/responses-saludos.js) palabras"
Salida

saludos.js: 2048 palabras
